<?php
header( 'content-type:text/plain' );
include 'config/config.php';
$token = $_GET['pdf'];
$tktqry = mysqli_query( $config, "SELECT * FROM booking WHERE token='$token'" );
$tktrow = mysqli_fetch_assoc( $tktqry );
$ticketno = $tktrow['id'];
$customer = $tktrow['passengername'];
$vehicle = $tktrow['regplate'];
$customerphone = $tktrow['passengerphone'];
$journey = $tktrow['from'].'-'.$tktrow['to'];
$cost = $tktrow['cost'];
$date = $tktrow['date'];
$time = $tktrow['departuretime'];
$seat = $tktrow['seat'];
$logo = 'images/logo.jpeg';
require( 'fpdf/fpdf.php' );
$pdf = new FPDF();
$pdf->AddPage();
//add logo
//$pdf->Image( $logo, 10, 6, 30 );
//$pdf->Ln( 5 );
$pdf->SetFont( 'Arial', 'B', 8 );
$pdf->Cell( 20, 8, 'Carry Me ', 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 20, 8, 'P.O Box 2782', 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 20, 8, '10100-Nyeri, Kenya ', 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 20, 8, 'Email: info@carryme.com ', 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 20, 8, 'Tel: 0717233580 ', 0, 0, L );
$pdf->Ln( 10 );
$pdf->Cell( 40, 8, 'Bus Ticket', 0, 0, C );
$pdf->Ln( 10 );
$pdf->SetFont( 'Arial', '', 8 );
$pdf->Cell( 10, 8, 'Customer Name: '.$customer, 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, 'Customer Phone: '.$customerphone, 0, 0, L );
$pdf->Ln( 8 );
$pdf->Cell( 10, 8, 'Vehicle Registration: '.$vehicle, 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, 'Seat Number: '.$seat, 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, 'Travel Date: '.$date, 0, 0, L );
$pdf->Ln( 4 );
$pdf->Cell( 10, 8, 'Departure Time: '.$time, 0, 0, L );
$pdf->Ln( 8 );
$pdf->SetFont( 'Arial', 'B', 6 );
$pdf->Cell( 10, 8, 'NOTE: Please be at the bus station 30 minutes before departure time.', 0, 0, L );
$pdf->Output( 'D', 'Ticket'.$ticketno.'.pdf', false );
?>